<?php
$this->headTitle()->append($this->translate('Manage Users'));
//$role =  Zend_Auth::getInstance()->getIdentity()->roleId;

//$this->headMeta('keyword', 'noF');asdafasfasfasfa
//file for upload imagesjquery-ui-1.8.16.custom.min.js
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/userList.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/jquery-ui-1.8.16.custom.css" );
?>
<style>



	 div.dataTables_wrapper table tbody tr td
{
    padding-bottom: 15px;
}
.modal.fade.in{
	top: 66% !important ;
}

</style>
<!-- Div for user list  -->

 <div id='userListDiv'>
		<div class='wrap columns-2'>
		<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
		<br><div class ="mainpage-content-colorbox success" id="removemsg">
		<?php if($this->messageSuccess!=''){?>
		<span class="successserver"><?php echo $this->messageSuccess; ?></span>
		<?php }?>
		<?php if($this->messageError!=''){?>
		<span class="errorserver"><?php echo $this->messageError; ?></span>
		<?php } ?>
		</div>
		<?php 
		}?>
		
<h1 class="fl"><?php echo $this->translate('Manage Users');?>

<!--  <input type="button" onClick="window.location.href='<?php //echo HTTP_PATH; ?>admin/user/adduser'" Value='<?php //echo $this->translate('Add New User'); ?>' name='addNew' class="btn ml10" />-->

</h1><a href="<?php //echo HTTP_PATH.'admin/user/trash/';?>" class="red trash-link"><strong><?php // echo $this->translate('Trash');?></strong></a>
          	<div class="clear"></div>
         
         <div class="mainpage-content-colorbox">
                <form class="form-search" onSubmit="return false;">
                   <div class="fl">                   
                          <input type="text" id='searchUser' name='search' placeholder="Search User" class="span5">
                        <button type='button' onclick="javascript:getUserList(search.value)" class="btn btn-primary">Search</button>
                    
                   </div>             	 

                   
                </form>
            
            </div>  
            
		<table  id="userList" class="table table-bordered table-striped">
			<thead>
	            <tr>
	             	<th ><?php echo $this->translate('id'); ?></th>
	             	<th ><?php echo $this->translate('Name'); ?></th>
	                <th><?php echo $this->translate('Email'); ?></th>
	                <th><?php echo $this->translate('Mobile'); ?></th>
	                <th><?php echo $this->translate('Barred');?></th>
	                <th><?php echo $this->translate('Delete');?></th>
	                
	               
	            </tr>
	        </thead>
	    </table>
	</div>
</div>
<!-- End code of list users -->

