<!-- <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/> -->
<!-- <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script> -->
<?php
echo $this->headTitle()->append('Trashed Users List');
$role =  Zend_Auth::getInstance()->getIdentity()->roleId;
if($role=='1' || $role=='2'){
//$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.js");	
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/trashedUserList.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/jquery-ui-1.8.16.custom.css" );

?>
<!-- Div for user list  -->
<div class='wrap columns-2"' id='userListDiv'>
<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
<br><div class ="mainpage-content-colorbox success">
<?php if($this->messageSuccess!=''){?>
<span class="successserver"><?php echo $this->messageSuccess; ?></span>
<?php }?>
<?php if($this->messageError!=''){?>
<span class="errorserver"><?php echo $this->messageError; ?></span>
<?php } ?>
</div></br>
<?php }?>
		<h1>Trash User List
		 <button class="btn ml10" href="#" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/user/'">Cancel</button>
		</h1>
		<div class="mainpage-content-colorbox">
                <form class="form-search" onSubmit="return false;">
                    <div class="fl">                   
                         <input type="text" id='tags' name='search' placeholder="Search User" class="span5">
                        <button  onclick="javascript:getUserListFromTrash(search.value,'undefine');"  class="btn btn-primary">Search</button>
                    
                    </div>             	
                    <div class="fl ml15 fillterDiv"> 
                      <select id='selectRole'>
                      </select>
                    </div>                         
                </form>
         </div>  
		<table id="trashUserList" class="table table-bordered table-striped">
			<thead>
	            <tr>
	            	<th><?php echo $this->translate('Id'); ?></th>
	                <th><?php echo $this->translate('Name'); ?></th>
	                <th class='maxWidth-email'><?php echo $this->translate('Email'); ?></th>
	                <th><?php echo $this->translate('Role'); ?></th>
	              	<th class="minwidth"><?php echo $this->translate('Entries');?></th>
	                <th class="minwidth"><?php echo $this->translate('Restore');?></th>
	                <th class="minwidth"><?php echo $this->translate('Delete');?></th>
  	            </tr>
	        </thead>
	    </table>
</div><!-- End code of list users -->
 <?php 
}
 ?>