<center>
	<div style='font-size: 20px;font-weight: bold;'>
	</br>
		Welcome to India Trip Holiday Administrator panel
	</div>
</br>
</br>
</br>
	 <div class="row dashboard-stats">
        <div class="section-1">
                        <!-- <div class="col-md-3 col-sm-6">
                            <section class="panel panel-box">
                                <div class="panel-left panel-icon bg-success">
                                    <i class="fa fa-inr text-large stat-icon success-text"></i>
                                </div>
                                <div class="panel-right panel-icon bg-reverse">
                                    <p class="size-h1 no-margin countdown_first">1050</p>
                                    <p class="text-muted no-margin text"><span>Profit</span></p>
                                </div>
                            </section>
                        </div> -->
                        <div class="col-md-3 col-sm-6">
                            <section class="panel panel-box">
                                <div class="panel-left panel-icon bg-danger">
                                    <i class="fa fa-shopping-cart text-large stat-icon danger-text"></i>
                                </div>
                                <div class="panel-right panel-icon bg-reverse">
                                    <p class="size-h1 no-margin countdown_second">152</p>
                                    <p class="text-muted no-margin text"><span>Orders</span></p>
                                </div>
                            </section>
                            
                        </div>
            
        </div>
        <div class="section-2">
                        <!-- <div class="col-md-3 col-sm-6">
                            <section class="panel panel-box">
                                <div class="panel-left panel-icon bg-lovender">
                                    <i class="fa fa-rocket text-large stat-icon lovender-text"></i>
                                </div>
                                <div class="panel-right panel-icon bg-reverse">
                                    <p class="size-h1 no-margin countdown_third">91<span class="size-h3">%</span></p>
                                    <p class="text-muted no-margin text"><span>Growth</span></p>
                                </div>
                            </section>
                        </div> -->

                        <div class="col-md-3 col-sm-6">
                            <section class="panel panel-box">
                                <div class="panel-left panel-icon bg-info">
                                    <i class="fa fa-users text-large stat-icon info-text"></i>
                                </div>
                                <div class="panel-right panel-icon bg-reverse">
                                    <p class="size-h1 no-margin countdown_fourth">99</p>
                                    <p class="text-muted no-margin text"><span>Users</span></p>
                                </div>
                            </section>
                        </div>    
        </div>
        </div> 
	  	
		

</center>
