<?php
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/login.js");

?>



<style>
<!--
.logostyle{
	height: 75px;
    margin:  0 0 0 0px;
    width: 330px;
    font-size: 32px;
	font-weight:normal;
	color:#278096;
	letter-spacing:1pt;
	word-spacing:2pt;
	text-align:center;
	font-family:lucida sans unicode, lucida grande, sans-serif;
	line-height:1;
	font-weight: bold;
}
-->
</style>
<?php $logoname = "Bleeper Admin Panel"; ?>
<form name="forgotpwd" id="forgotpwd" action="" method="post"><div class="login-box-outer">
	<div class="login-logo logostyle">
    <?php echo $this->translate($logoname);?>
    <!--  <img src="<?php //echo PUBLIC_PATH?>images/back_end/imbull-login-logo.jpg" border="0" />-->
    </div>
	<div class="login-box">
    	<div class="login-box-heading"><?php echo $this->translate('Forgot Password?');?></div>
    	<span class='login-input error' id='error-msg'> 
    	<?php
	    	 echo $this->message;
	    	 	
	    ?>
    	</span>
    	
    	<div class="input-prepend login-input">
          <span class="add-on"><i class="icon-envelope"></i></span><input type="text" name="email" id="email" maxlength="254" placeholder="Username/E-mail Address">
        </div>
        <div class="button-outer">
        <button type="submit" name="button" id="button" class="btn btn-large btn-primary" ><?php echo $this->translate('REQUEST NEW PASSWORD');?></button>
         <a id='back' href="<?php echo HTTP_PATH?>admin/auth"><?php echo $this->translate('Back to Login');?></a>
        </div>
    </div>
</div></form>