<?php 
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/login.js");
// $this->headScript()->appendFile(PUBLIC_PATH . "/js/common.js");
?>
<style>

.logostyle{
	/*height: 75px;*/
    margin:  0 0 0 30px;
    width: 330px;
    font-size: 32px;
	font-weight:normal;
	color:#278096;
	letter-spacing:1pt;
	word-spacing:2pt;
	text-align:center;
	font-family:lucida sans unicode, lucida grande, sans-serif;
	line-height:1;
	font-weight: bold;
}

</style>

<?php $logoname = "Admin Panel"; ?>
<form name="form1" action='' id="form1"  method="post"    >
	<div class="login-box-outer" >
	
		 <div class="login-logo logostyle" >
	    	<?php //echo $this->translate($logoname);?>
	    	<img src="<?php echo PUBLIC_PATH; ?>images/front_end/logo.png" border="0" /> 
	    </div> 
		<div class="login-box">
	    	<div class="login-box-heading"><?php echo $this->translate('Administrator panel');?></div>
	    	
	    	<div class='login-input error' id='error-msg' style = "height : 14px; margin-top: 15px; color: #B94A48;">
	    	<?php
	    	  	echo $this->message;
	    	 	
	    	?></div>
	    	<div class="input-prepend login-input" >
	    	
	          	<span class="add-on"><i class="icon-user"></i></span>
	          	<input type="text" maxlength="254" placeholder="<?php echo $this->translate("Username")?>" name="uname" id="uname" value="<?php if($this->personemail!='') echo $this->personemail;{?><?php }?>">
	          	
	        </div>
	        <div class="input-prepend login-input1">
	          <span class="add-on"><i class="icon-lock"></i></span><input type="password"  maxlength="20" placeholder="<?php echo $this->translate("Password")?>" name="pwd" id="pwd">
	        </div>
	        <div class="button-outer">
	
	        <button type="submit" name="button" id="button" class="btn btn-large btn-primary"><?php echo $this->translate('SIGN IN');?></button>
					<!-- <a href="<?php echo HTTP_PATH;?>admin/auth/forgotpassword"><?php //echo $this->translate('Forgot Password?');?></a> -->
					
	        </div>
	    </div>
	</div>
</form>