<div class="login-box-outer">
	<div class="login-logo">
    	<img src="<?php echo PUBLIC_PATH?>images/back_end/imbull-login-logo.jpg" border="0" />
    </div>
	<div class="login-content-colorbox">Logout successfully</div>
    <div class="button-outer-success">
        <a href="<?php echo HTTP_PATH;?>auth"><button class="btn btn-large btn-primary"><strong>BACK TO LOGIN</strong></button></a>
    </div>

</div>