<div id="imbullwrap">
<div class="login-box-outer">
	<div class="login-logo">
    	<img src="<?php echo PUBLIC_PATH.'images/back_end/imbull-login-logo.jpg';?>" border="0" /> 
    </div>
	<div class="login-content-colorbox"><?php echo $this->translate('Check your email address for a new password');?></div>
    <div class="button-outer-success">
        <button onClick="(window.location='<?php echo HTTP_PATH;?>admin/auth')" class="btn btn-large btn-primary"><strong><?php echo $this->translate('BACK TO LOGIN');?></strong></button>
    </div>

</div>
 
</div>
<!-- imbullwrap --> 
