        <!-- Start Main Content -->
        <div class="main-content">
        <div class="container">
        <div class="row">
        
        <h2>Terms and Conditions</h2>
        <div class="separator">
        </div>
        
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In non finibus nisl. Maecenas auctor ligula eget eros vestibulum, sed feugiat dui viverra. Nulla aliquam, lorem id fermentum rhoncus, arcu nisl sagittis nulla, et placerat velit tellus eget turpis. Vivamus ut bibendum nulla. Nunc tristique et velit vel dictum. Morbi sagittis odio non massa posuere, volutpat varius dui congue. Sed in fringilla libero, ullamcorper luctus ligula. Aliquam dui dolor, rhoncus quis porttitor ut, eleifend eget ipsum.

Nulla auctor dui id quam pellentesque consequat. Aliquam eu mattis nisl. Nulla luctus magna id ex fermentum rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean ac mi interdum quam tincidunt fringilla non a urna. Vivamus dictum eget urna quis sodales. Sed sed ante id mi aliquet tincidunt.


Lorem ipsum dolor sit amet, consectetur adipiscing elit. In non finibus nisl. Maecenas auctor ligula eget eros vestibulum, sed feugiat dui viverra. Nulla aliquam, lorem id fermentum rhoncus, arcu nisl sagittis nulla, et placerat velit tellus eget turpis. Vivamus ut bibendum nulla. Nunc tristique et velit vel dictum. Morbi sagittis odio non massa posuere, volutpat varius dui congue. Sed in fringilla libero, ullamcorper luctus ligula. Aliquam dui dolor, rhoncus quis porttitor ut, eleifend eget ipsum.

Nulla auctor dui id quam pellentesque consequat. Aliquam eu mattis nisl. Nulla luctus magna id ex fermentum rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean ac mi interdum quam tincidunt fringilla non a urna. Vivamus dictum eget urna quis sodales. Sed sed ante id mi aliquet tincidunt.</p>
        
       
    </div>
    	</div>
    	</div>
