<div id="main-content" class="site-main clearfix">
    <div id="content-wrap">
        <div id="site-content" class="site-content clearfix">
            <div id="inner-content" class="inner-content-wrap">
                <div class="page-content">
                    <!-- GALLERY -->

                    <section class="wprt-section">
                        <div class="container">
                            <div class="row">
                             <div class="col-md-12">
                                    <div class="wprt-spacer" data-desktop="40" data-mobi="60" data-smobi="60" style="height:40px"></div>
                                </div><!-- /.col-md-12 -->

                                <div class="col-md-8">
                                    <h2 class="line-height-normal margin-bottom-10"> <?php echo $this->pageInfo["pageTitle"] ?></h2>
                                    <div class="wprt-lines style-1 custom-3">
                                        <div class="line-1"></div>
                                        <div class="line-2"></div>
                                    </div>

                                    <div class="wprt-spacer" data-desktop="25" data-mobi="25" data-smobi="25" style="height:25px"></div>

                                    <p class="margin-bottom-25">
                                    <?php echo $this->pageInfo["content"] ?></p>
                                </div><!-- /.col-md-8 -->

                                <div class="col-md-4">
                                <div class="side-bar">
                                  <h2 class="line-height-normal margin-bottom-10">TOP Story</h2>
                                  <div class="wprt-lines style-1 custom-3">
                                        <div class="line-1"></div>
                                        <div class="line-2"></div>
                                    </div>
                    <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FIndiatripholidaycom-167430244036097%2F&tabs=timeline&width=340&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="340" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>

                                </div><!--side-bar-->
                                </div><!-- /.col-md-4 -->

                                <div class="col-md-12">
                                    <div class="wprt-spacer" data-desktop="80" data-mobi="60" data-smobi="60" style="height:80px"></div>
                                </div>
                            </div><!-- /.row -->
                        </div><!-- /.container -->
                  </section>

                </div>
            </div>
        </div>
    </div>
</div>