<div id="main-content" class="site-main clearfix">
    <div id="content-wrap">
        <div id="site-content" class="site-content clearfix">
            <div id="inner-content" class="inner-content-wrap">
                <div class="page-content">
                    <section class="wprt-section">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="wprt-spacer" data-desktop="80" data-mobi="60" data-smobi="60" style="height:80px"></div>
                                    <iframe width="1100" height="350" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=Indiatripholiday.com%20(A%20unit%20of%20SARTHEE)&key=AIzaSyDR_YYonB5IdVFKdSSmpgwcZ26ArTSIvQs" allowfullscreen></iframe>
                                    <div class="wprt-spacer" data-desktop="50" data-mobi="40" data-smobi="40" style="height:50px"></div>
                                </div><!-- /.col-md-12 -->



                                <div class="col-md-4">
                                    <div class="wprt-information">
                                    <?php 
                                          echo $this->contactusContent["content"];
                                     ?>
                                        <!-- <ul class="style-2">
                                            <li class="address">
                                                <span class="hl">Address:</span>
                                                <span class="text">SCO 85, 2nd Floor, Sector 35-C, Chandigarh, 160022</span>
                                            </li>
                                            <li class="phone">
                                                <span class="hl">Phone:</span> 
                                                <span class="text">+91 81-786-595-75</span>
                                            </li>
                                            <li class="email">
                                                <span class="hl">E-mail:</span>
                                                <span class="text">info@indiatripholiday.com</span>
                                            </li>
                                        </ul> -->
                                    </div><!-- /.wprt-information -->

                                    <div class="wprt-spacer" data-desktop="0" data-mobi="30" data-smobi="30" style="height:0px"></div>
                                </div><!-- /.col-md-4 -->

                          <!-- <div class="col-md-8">
                            <h4 class="margin-bottom-15">GET IN TOUCH WITH US</h4>
                  <form method="post" class="contact-form wpcf7-form" novalidate="novalidate">
                    <div class="wprt-contact-form-1">
                      <span class="wpcf7-form-control-wrap name">
                        <input type="text" tabindex="1" id="name" name="name" value="" class="wpcf7-form-control" placeholder="Name *" required="">
                      </span>
                      <span class="wpcf7-form-control-wrap email">
                        <input type="email" tabindex="2" id="email" name="email" value="" class="wpcf7-form-control" placeholder="E-mail *" required="">
                      </span>
                      <span class="wpcf7-form-control-wrap phone">
                        <input type="text" tabindex="3" id="phone" name="phone" value="" class="wpcf7-form-control" placeholder="Phone Number">
                      </span>
                      <span class="wpcf7-form-control-wrap subject">
                        <input type="text" tabindex="4" id="subject" name="subject" value="" class="wpcf7-form-control" placeholder="Subject *" required="">
                      </span>
                      <span class="wpcf7-form-control-wrap message">
                        <textarea name="message" tabindex="5" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea" placeholder="Message" required=""></textarea>
                      </span>
                      <div class="wrap-submit">
                        <input type="submit" value="SEND MESSAGE" class="submit wpcf7-form-control wpcf7-submit" id="submit" name="submit">
                      </div>
                    </div>
                  </form>
                          </div> -->

                                <div class="col-md-12">
                                    <div class="wprt-spacer" data-desktop="80" data-mobi="60" data-smobi="60" style="height:80px"></div>
                                </div><!-- /.col-md-12 -->
                            </div><!-- /.row -->
                        </div><!-- /.container -->
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>