   <!-- Page Content -->
  <div id="content">
    <div class="container">

        <div class="row">
            <div id="main-content">
                <article>
        <header>
        <div class="cars-list">
         
         <div class="row">
         
         <div class="col-sm-4">
         <div class="car-item">
         <img src="<?php echo PUBLIC_PATH; ?>images/front_end/2.shimla.city.jpg" />
        
         <div class="book-now">
         
         <div class="car-text">
         <h2>Small Business.<br> 
                     Big Savings.</h2>
                   <p>Save up to 20% off base rates<br> with Raftaar For Shimla.</p>
           <a href="<?php echo HTTP_PATH; ?>index/booknow">Book Now </a>
         </div>
         
         </div>
         </div>
        </div><!-- /.col-sm-4 -->
         
         <div class="col-sm-4">
         
          <div class="car-item">
         <img src="<?php echo PUBLIC_PATH; ?>images/front_end/dharamshala.jpg" />
        
         <div class="book-now">
         
         <div class="car-text">
         <h2>Small Business.<br> 
                     Big Savings.</h2>
                   <p>Save up to 10% off base rates <br>with Raftaar For DharamShala.</p>
           <a href="<?php echo HTTP_PATH; ?>index/booknow">Book Now </a>
         </div>
         
         </div>
         </div>
         
         </div><!-- /.col-sm-4 -->
         
         <div class="col-sm-4">
         <div class="car-item">
         <img src="<?php echo PUBLIC_PATH; ?>images/front_end/Rishikesh_._Lakshman_Jhula.jpg" />
        
         <div class="book-now">
         
         <div class="car-text">
         <h2>Small Business.<br> 
                     Big Savings.</h2>
                   <p>Save up to 30% off base rates <br>with Raftaar For Rishikesh.</p>
           <a href="<?php echo HTTP_PATH; ?>index/booknow">Book Now </a>
         </div>
         
         </div>
         </div>
         
         </div>
         
         <div class="col-sm-4">
         <div class="car-item">
         <img src="<?php echo PUBLIC_PATH; ?>images/front_end/citycar4.jpg" />
        
         <div class="book-now">
         
         <div class="car-text">
         <h2>Enjoy your Trip.<br> 
                     Hire Car.</h2>
                   <p>Save up to 30% off base rates <br>with Raftaar For Business.</p>
          <a href="<?php echo HTTP_PATH; ?>index/booknow">Book Now </a>
         </div>
         
         </div>
         </div>
         
         </div>
        
        <!-- /.col-sm-4 -->
         <div class="col-sm-4">
         <div class="car-item">
         <img src="<?php echo PUBLIC_PATH; ?>images/front_end/citycar5.jpg" />
        
         <div class="book-now">
         
         <div class="car-text">
         <h2>Raftaar Travel.<br> 
                     Make your trip Awesome.</h2>
                   <p>Your choise car <br>Raftaar will provide you.</p>
           <a href="<?php echo HTTP_PATH; ?>index/booknow">Book Now </a>
         </div>
         
         </div>
         </div>
         
         </div>
         
         <!-- /.col-sm-4 -->
         
         
         
         <div class="col-sm-4">
         <div class="car-item">
         <img src="<?php echo PUBLIC_PATH; ?>images/front_end/citycar6.jpg" />
        
         <div class="book-now">
         
         <div class="car-text">
         <h2>Small Business.<br> 
                     Big Savings.</h2>
                   <p>Save up to 30% off base rates <br>with Raftaar For Business.</p>
           <a href="<?php echo HTTP_PATH; ?>index/booknow">Book Now </a>
         </div>
         
         </div>
         </div>
         
         </div>
         
         <!-- /.col-sm-4 -->
         
         
         </div><!-- /. row -->
         
         </div>
         
         
        </article>
            </div>
      
        </div>
        <!-- /.row -->

    </div> <!-- /.container -->
  </div>