<?php 
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/datepicker.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/timepicker.css" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/addpage.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/jquery.NobleCount.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.textareaCounter.plugin.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-datepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-timepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js");
$this->headScript ()->appendFile (PUBLIC_PATH . "js/back_end/ckeditor/config.js" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/date.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/jquery-ui-1.8.16.custom.css" );
?>
<?php echo $this->headTitle()->append('Create Page');?>
<script type="text/javascript">

var CKEDITOR_BASEPATH = "<?php echo PUBLIC_PATH . "js/back_end/ckeditor/" ; ?>" ;

</script>
<div class="wrap columns-2">
         
          <h1><?php echo $this->translate('Create Page'); ?>
          <button type = "button" onClick="window.location.href='<?php echo HTTP_PATH;?>admin/page'" class="btn ml10" href="#"><?php echo $this->translate('Cancel'); ?></button>
         
          </h1>
          
           <form id="addPageform" name="addPageform" enctype="multipart/form-data" method="POST" action="<?php echo HTTP_PATH;?>admin/page/savepage">
           <input type="checkbox" name="selectedpageType" value="1" id="selectedpageType" class="display-none">
            <div class="metabox-holder has-right-sidebar" id="poststuff">
              <div class="inner-sidebar" id="side-info-column">
                <div class="meta-box-sortables ui-sortable" id="side-sortables">
                  <div class="postbox " id="submitdiv">
                    <div class="sidebar-heading">
	                    <p><?php echo $this->translate('Publish'); ?></p>
                    </div>
                    <!-- <div class="sidebar-content-box">
                        <button class="btn" type="submit" onClick="$('#savePage').val('draft')" href="#" id="saveDraftbtn" ><?php echo $this->translate('Save Draft'); ?></button>
                        <a href="<?php echo HTTP_PATH."preview/notpreview"; ?>" target="_blank"><button type = "button" class="btn" id="previewBtn"><?php echo $this->translate('Preview'); ?></button></a>
                    </div> -->
                    <input type="hidden" name="savePagebtn" id="savePage" value="">
                    <!-- <div class="sidebar-content-box">
                        <?php echo $this->translate('Status:'); ?> <strong><?php echo $this->translate('Draft'); ?></strong>
                    </div> -->
                   <!-- <div class="sidebar-content-box">
                        <?php echo $this->translate('Publish'); ?> <strong><?php echo $this->translate('immediately'); ?> <a href="javascript:;" onClick="showPublishDate()" id="editpublishLink"><?php echo $this->translate('Edit'); ?></a></strong>
                    <span id="publishlater" class="display-none">
                    <input type="text" style="width:110px;margin-top:3px;" value="<?php echo date('d-m-Y');?>" placeholder="Publish Date"  id="publishDate" name="publishDate" class="span3">
                     <input type="text" style="width:48px;margin-top:3px;" placeholder="HH" id="publishTimehh" name="publishTimehh" class="span3">
                    <div id="publisherror"></div>
                     </span>
                    
                     </div> -->
                    <div class="sidebar-box-footer">
                        <button id="publishBtn" onClick="$('#savePage').val('publish')" class="btn btn-primary fr" href="#"><?php echo $this->translate('Publish'); ?></button>
                        <a style="margin: 0 10px 0 0 !important;" class="btn m5" href="<?php echo HTTP_PATH;?>admin/page" id="publishcancelBtn"><?php echo $this->translate('Cancel'); ?></a>
                    </div>
                  </div>
                  
                
                </div>
              </div>
              <div id="post-body">
              	<div id="post-body-content">
              		<div class="mainpage-content">
                    	<div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Page title'); ?></strong></label></div>
                            <div class="mainpage-content-right"><input type="text" name="pageTitle" id="pageTitle" class="span3" placeholder="<?php echo $this->translate('Page title'); ?>"></div>
                        	<div class="mainpage-content-right" style="height : 20px;"></div>
                        </div>
                        <!-- <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Permalink'); ?></strong></label></div>

                            <div class="mainpage-content-right"><div class="mainpage-content-right-inner-left"><label>http://www.kortingscode.nl/</label></div><div class="mainpage-content-right-inner-right"><input type="text" class="span3" name="pagepermalink" id="pagepermalink" placeholder="<?php echo $this->translate('permalink'); ?>"></div>
                             <div class="mainpage-content-right" style="float:left;margin:-9px 0 6px 0; height : 20px; width : 511px;"></div>

                            </div>
                       </div> -->
                         <!-- <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Image'); ?></strong></label></div>
                            <div class="mainpage-content-right"><input type="file" onchange="checkFileType(event)" class="ignore"   name="logoFile" id="pageImage"><span><?php echo $this->translate('.jpg or .png file only (Size: 2MB, Ratio: 0.75)'); ?></span></div>
                        <div class="mainpage-content-right" id="imagerrorDiv" style="float:left;margin:-9px 0 6px 218px; height : 20px; width : 511px;"></div>
                        </div> -->
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Meta title'); ?></strong></label></div>
                            <div class="mainpage-content-right"><input type="text" name="pagemetaTitle" id="pagemetaTitle" placeholder="<?php echo $this->translate('Meta title');?>" class="input-xlarge mbot bbot ignore"/>
							<input type="text" disabled="disabled" value="<?php echo $this->translate('0 characters');?>" id="metaTextLeft" class="input-xlarge disabled btop word-count">
							<!--<span id="metaTextLeft" class="nobel" style="width:504px;"></span>-->
                            
                            <!--<input type="text" class="span3" placeholder="<?php //echo $this->translate('Meta Title'); ?>" name="pagemetaTitle" maxlength="68" id="pagemetaTitle">-->
                            </div>
                        </div>
                      <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Meta Description'); ?></strong></label></div>
                            <div class="mainpage-content-right"><textarea class="input-xlarge mbot bbot ignore" id="pagemetaDesc" name="pagemetaDesc" placeholder="<?php echo $this->translate ( 'Meta Description' );?>" rows="3"></textarea>
							<input type="text" disabled="disabled" value="<?php echo $this->translate('0 characters');?>" id="metaDescLeft" class="input-xlarge disabled btop word-count">
							<!--<span id="metaDescLeft" class="nobel" style="width:504px;"></span>-->
                            
                            <!--<textarea class="input-xlarge mbot bbot ignore" name="pagemetaDesc" id="pagemetaDesc" placeholder="<?php //echo $this->translate('Meta Description'); ?>"  rows="3"></textarea>
                            <input type="text" class="input-xlarge disabled btop word-count"  id="metaTextLeft" value = "Characters Left: 160" placeholder="Word Count: 28" disabled="disabled">-->
                            </div>
                        </div>
                    </div>
                	<textarea class="input-xlarge" name="pageDesc" id="pageDesc" placeholder="<?php echo $this->translate('Page Description'); ?>" rows="10"></textarea>
                  <br><div id="offerconstraint" class="display-none"> 
                
                <!-- <div class="mainpage-content">
                    	<div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Maximum Offers on Page'); ?></strong></label></div>
                            <div class="mainpage-content-right"><input type="text" name="maxOffer" id="maxOffer" class="span3" placeholder="<?php echo $this->translate('Maximum Offer'); ?>"></div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Offers Order'); ?></strong></label></div>
                           <div class="btn-group" data-toggle="buttons-checkbox">
                                        <button type="button" onClick="setOffersOrder('ascendingOffer')" id="ascendingOffer" class="btn btn-primary">ascending</button>                     
                                        <button type="button" onClick="setOffersOrder('descendingOffer')" id="descendingOffer" class="btn">descending</button>
                                        <input type="checkbox" id="offersOrderchk" value="1" name="offersOrderchk" checked="checked" class="display-none">
                            </div>
                        </div>
                 </div> 
                    <div class="edit-page-box-new">
                    	<div class="mainpage-content-line">
                        	<label class="checkbox">
                                <input type="checkbox" value="1" onClick="constraint(event,'time')" id="timeCostraintchk" name="timeCostraintchk"> <strong><?php echo $this->translate('Enable time constraint');?></strong>
                            </label>
                            <div class="line"></div>
                            <div class="edit-page-feilds display-none" id="showTimeConstraint">
                            	<div class="fl">
                            	<select id="postwithin" name="postwithin">
                                    <option value="1"><?php echo $this->translate('Posted within'); ?></option>
                                    <option value="2"><?php echo $this->translate('Expires in'); ?></option>
                                 </select>
                                </div>
                                <div class="fl ml15">
                                    <input type="text" id="numberofDays" name="numberofDays"  class="span1 ml15" placeholder="10">                                   
                                </div>
                                <div class="fl ml15">                                  
                                    <p class="mr15"><?php echo $this->translate('Days'); ?></p>
                                </div>
                               
                            </div>
                        </div>
                        
                        </div>
                         <div class="edit-page-box-new">
                            <div class="mainpage-content-line">
                                <label class="checkbox">
                                    <input type="checkbox" value="1" onClick="constraint(event,'word')" id="wordCostraintchk" name="wordCostraintchk"> <strong><?php echo $this->translate('Word constraint'); ?></strong>
                                </label>
                                <div class="line"></div>
                                <div class="edit-page-feilds display-none" id="wordConstraint">
                                    <div class="fl mr15">
                                    <input type="text" id="wordConstraintTxt" name = "wordConstraintTxt" class="span5" placeholder="<?php echo $this->translate('Word constraint'); ?>"> 
                                    </div>                                
                                 </div>
                            </div>                        
                        </div> -->
                        
                      <!--   <div class="edit-page-box-new">
                            <div class="mainpage-content-line">
                                <label class="checkbox">
                                    <input type="checkbox" value="1" onClick="constraint(event,'award')" id="awardCostraintchk" name="awardCostraintchk" > <strong><?php echo $this->translate('Awards');?></strong>
                                </label>
                                <div class="line"></div>
                                <div class="edit-page-feilds display-none" id="awardConstraint">
                                    <div class="fl mr15">
                                        <select id="select02" id="awardConstraintDropdown" name="awardConstraintDropdown">
                                            <option value="1"><?php echo $this->translate('Free shipping'); ?></option>
                                            <option value="2"><?php echo $this->translate('Order today,delivered tomorrow'); ?></option>
                                        </select>                                        
                                    </div>                                
                                 </div>
                            </div>                        
                        </div> -->
                        
                        <!-- <div class="edit-page-box-new">
                            <div class="mainpage-content-line">
                                <label class="checkbox">
                                    <input type="checkbox" value="1" onClick="constraint(event,'clicks')" id="clickCostraintchk" name="clickCostraintchk"> <strong><?php echo $this->translate('Clickouts'); ?></strong>
                                </label>
                                <div class="line"></div>
                                <div class="edit-page-feilds display-none" id="clickConstraint">
                                    <div class="fl mr15">
                                    <input id="clickConstraintTxt" name="clickConstraintTxt" type="text" class="span3" placeholder="<?php echo $this->translate('Clickouts'); ?>"> 
                                    </div>
                                    <div class="fl">
                                        <p class="mr15"><?php echo $this->translate('Of clickouts'); ?></p>
                                    </div>                                
                                 </div>
                            </div>                        
                        </div> -->
             <!--    <div class="mainpage-content">
                        <strong><?php echo $this->translate('Show offer types'); ?></strong>                               
                        <div class="line"></div>
                    	<div class="mainpage-content-line mb10">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Coupon'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="btn-group" data-toggle="buttons-checkbox">
                                    <button id="regularCoupon" onClick="offerType('regularCoupon','coupon','regular')" type = "button" class="btn"><?php echo $this->translate('Regular');?></button>                     
                                    <button id="editorPickCoupon" onClick="offerType('editorPickCoupon','coupon','editor')" type = "button" class="btn"><?php echo $this->translate('Editors pick'); ?></button>
                                    <button id="exclusiveCoupon" onClick="offerType('exclusiveCoupon','coupon','exclusive')" type = "button" class="btn"><?php echo $this->translate('Exclusive'); ?></button>
                                  </div>
                                  <input type="checkbox" id="coupconCoderegularchk" name="coupconCoderegularchk" value="1" class="display-none"> 
                                  <input type="checkbox" id="coupconCodeeditorchk" name="coupconCodeeditorchk" value="1" class="display-none"> 
                                  <input type="checkbox" id="coupconCodeeclusivechk" name="coupconCodeeclusivechk" value="1" class="display-none"> 
                            </div>
                        </div> -->
                        <?php /* ?>
                        <div class="mainpage-content-line mb10">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Sale'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="btn-group" data-toggle="buttons-checkbox">
                                    <button id="regularSale" type = "button" onClick="offerType('regularSale','sale','regular')" class="btn"><?php echo $this->translate('Regular'); ?></button>                     
                                    <button id="editorPickSale" type = "button" onClick="offerType('editorPickSale','sale','editor')" class="btn"><?php echo $this->translate('Editors pick'); ?></button>
                                    <button id="exclusiveSale" type = "button" onClick="offerType('exclusiveSale','sale','exclusive')" class="btn"><?php echo $this->translate('Exclusive'); ?></button>
                                  </div>
                                   <input type="checkbox" id="saleregularchk" name="saleregularchk" value="1" class="display-none"> 
                                   <input type="checkbox" id="saleeditorchk" name="saleeditorchk" value="1" class="display-none"> 
                                  <input type="checkbox" id="saleeclusivechk" name="saleeclusivechk" value="1" class="display-none">
                            </div>
                        </div>
                         <div class="mainpage-content-line mb10">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Printable'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="btn-group" data-toggle="buttons-checkbox">
                                    <button id="regularPrintable" type = "button" onClick="offerType('regularPrintable','printable','regular')" class="btn"><?php echo $this->translate('Regular');?></button>                     
                                    <button id="editorPickPrintable" type = "button" onClick="offerType('editorPickPrintable','printable','editor')" class="btn"><?php echo $this->translate('Editors pick'); ?></button>
                                    <button id="exclusivePrintable" type = "button" onClick="offerType('exclusivePrintable','printable','exclusive')" class="btn"><?php echo $this->translate('Exclusive');?></button>
                                  </div>
                                   <input type="checkbox" id="printableregularchk" name="printableregularchk" value="1" class="display-none"> 
                                   <input type="checkbox" id="printableeditorchk" name="printableeditorchk" value="1" class="display-none"> 
                                   <input type="checkbox" id="printableexclusivechk" name="printableexclusivechk" value="1" class="display-none">
                            </div>
                        </div>  
                        <?php */ ?>                      
                    </div>
                    
                    
                    <!-- <div style="height:28px;" class="mainpage-content">
                    	<div class="mainpage-content-line m10">
                        	<div class="fl">
                            	<strong><?php echo $this->translate('Show as page when creating offers?'); ?></strong>
                            </div>
                        	<label class="checkbox fl ml15">
                                 <input type="radio" name="showPage" value = "1"><sup>  <?php echo $this->translate('Yes'); ?> </sup>
                            </label>
                            <label class="checkbox fl ml15">
                                 <input type="radio" name="showPage" value = "0" checked="checked"> <sup>  <?php echo $this->translate('No'); ?> </sup>
                            </label>                           
                        </div>                        
                     </div> -->
       </div>                    
                        
                        
                        
                    </div>
                </div>
              </div>
                <input type="hidden" name="pageId" id="pageId" value="" >
            </form>  
              <br class="clear">
</div>