<?php
$this->headTitle()->append($this->translate('Edit Song'));
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.ui.widget.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.iframe-transport.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload-fp.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload-ui.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/songsList.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/jquery-ui-1.8.16.custom.css" );
?>
<style>
<!--
#someID{
	margin-left:215px;
}
-->
</style>
<!-- Div for add edit user list  -->
<div id='editUserDiv' class="wrap columns-2">
         <h1><?php  echo $this->translate('Edit Songs'); ?></h1>
         <form name=addSongs method = "POST" action = '' id='addSongs' enctype="multipart/form-data">
				<div id="poststuff" class="metabox-holder has-right-sidebar">
              <div id="post-body">
              	<div>
              	
              		<div class="mainpage-content">
                    		<div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Songs Name'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other"><input type="text" value = "<?php echo $this->dataSongs['songName']; ?>" name="SongsName" id="SongsName"  placeholder="<?php echo $this->translate('Songs Name'); ?>" class="span3"></div>                        
                            </div>
                        </div>
                                                
                 <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Artist Name'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other"><input type="text" value = "<?php echo $this->dataSongs['artistName']; ?>" name="ArtistName" id="ArtistName"  placeholder="<?php echo $this->translate('Artist Name'); ?>" class="span3"></div>                        
                            </div>
                        </div>
                    <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php  echo $this->translate('Lyrics'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other" style="border-bottom-width: 0px; margin-bottom: 10px;" >
							<textarea class="input-xlarge mbot bbot ignore"  id="Address"  placeholder="<?php echo $this->translate('Lyrics'); ?>" name="Lyrics" rows="20" ><?php echo $this->dataSongs['lyrics']; ?></textarea>
                    	</div>
                    </div>
                        </div>
                        
                
            	<button  id="saveSongs" type="submit" class="btn btn-large btn-primary fl"><?php echo $this->translate('UPDATE'); ?></button>
                <a href="<?php echo HTTP_PATH; ?>admin/songs"  class="fl m10"><strong><?php echo $this->translate('CANCEL'); ?></strong></a>
  
            </form>
        </div>
