<!-- Main Content -->
<div id="main-content" class="site-main clearfix">
    <div id="content-wrap">
        <div id="site-content" class="site-content clearfix">
            <div id="inner-content" class="inner-content-wrap">
                <div class="page-content">
                    <section class="wprt-section">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="wprt-spacer" data-desktop="80" data-mobi="60" data-smobi="60"></div>
                                </div><!-- /.col-md-12 -->

                                <div class="col-md-4">
                                    <div class="project-image">
                                        <img src="<?php echo PUBLIC_PATH; ?>images/upload/products/medium/thum_medium_<?php echo $this->showproduct["image"] ; ?>" class="img-fluid" />
                                    </div>
                                </div><!-- /.col-md-8 -->

                                <div class="col-md-8">
                                    <div class="wprt-spacer" data-desktop="0" data-mobi="40" data-smobi="40"></div>

                                    <h3 class="line-height-normal margin-bottom-10">DESCRIPTION</h3>
                                    <div class="wprt-lines style-1 custom-3">
                                        <div class="line-1"></div>
                                        <div class="line-2"></div>
                                    </div>

                                    <div class="wprt-spacer" data-desktop="25" data-mobi="25" data-smobi="25"></div>

                                    <p><?php echo ucfirst($this->showproduct["description"]) ; ?></p>

                                    <div class="wprt-lines style-1 custom-4">
                                        <div class="line-1"></div>
                                    </div>

                                    <ul class="wprt-list style-2 accent-color margin-top-30 margin-bottom-25">
                                        <!-- <li><strong>Client:</strong> ThemeForest Builder</li>
                                        <li><strong>Architect:</strong> Richardson and Sandra</li>
                                        <li><strong>Builder:</strong> GraphicRiver Builder Corporate</li> -->
                                        <li><strong>Cost:</strong> ₹ <?php echo $this->showproduct["price"] ; ?></li>
                                    </ul>

                                    <a href="<?php echo HTTP_PATH.'index/booknow' ; ?>" class="wprt-button small rounded-3px">Book Now</a>
                                </div><!-- /.col-md-4 -->

                                <div class="col-md-12">
                                    <div class="wprt-spacer" data-desktop="80" data-mobi="60" data-smobi="60"></div>
                                </div><!-- /.col-md-12 -->
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>