
<!-- Hero Background SlideShow -->
<div id="hero-section" data-number="2" data-image-1="<?php echo PUBLIC_PATH; ?>images/front_end/s1.jpg" data-image-2="<?php echo PUBLIC_PATH; ?>images/front_end/s2.jpg" data-effect="fade">
    <div class="hero-content">
        <div class="hero-title scroll" data-min="28px" data-max="80px">
            <h1>WELCOME</h1>
            <h1>INDIATRIPHOLIDAY</h1>
            <h1>WHAT WE DO</h1>
        </div>

        <div class="hero-text">
            <p>Best deals for your Travel and Holiday packages for International and India tourist destinations. Customized packages and special deals on Hotel bookings, ensuring customer experience and value for money.</p>
        </div>

        <div class="hero-button">
            <a class="wprt-button rounded-3px" href="<?php echo HTTP_PATH.'index/aboutus' ; ?>">LEARN MORE</a>
        </div>
    </div><!-- /.hero-content -->

    <a class="arrow scroll-target" href="#destinations-section"></a><!-- change href value to ID of section you want to scroll down -->
</div>

