<?php
ob_start("ob_gzhandler");
?>
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US"><!--<![endif]-->
<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->    
    <meta name="author" content="India trip holiday">
    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Theme Style -->
       
<?php 
      $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/front_end/styleoz.css" );
echo $this->headStyle ();
echo $this->headLink ();
echo $this->headMeta ();
echo $this->headTitle ();

?>
<script type="text/javascript" src="<?php echo PUBLIC_PATH; ?>js/front_end/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH; ?>js/front_end/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH; ?>js/front_end/animsition.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH; ?>js/front_end/plugins.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH; ?>js/front_end/countTo.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH; ?>js/front_end/fitText.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH; ?>js/front_end/flexslider.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH; ?>js/front_end/vegas.js"></script>
<!-- <script type="text/javascript" src="<?php echo PUBLIC_PATH; ?>js/front_end/cube.portfolio.js"></script> -->
<script type="text/javascript" src="<?php echo PUBLIC_PATH; ?>js/front_end/main.js"></script>

    <!-- Favicon and touch icons  -->
    <link rel="shortcut icon" href="<?php echo PUBLIC_PATH; ?>images/front_end/favicon.png">
    <link rel="apple-touch-icon-precomposed" href="<?php echo PUBLIC_PATH; ?>images/front_end/favicon.png">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="front-page no-sidebar site-layout-full-width header-style-5 menu-has-search menu-has-cart">

<div id="wrapper" class="animsition" style="animation-duration: 1500ms; opacity: 1;">
<div id="page" class="clearfix">

<div id="site-header-wrap">
    <!-- Top Bar -->
    <div id="top-bar" class="style-2">
        <div id="top-bar-inner" class="container">
            <div class="top-bar-inner-wrap">
                 <div id="site-logo" class="clearfix">
                    <div id="site-logo-inner">
                        <a href="/" title="indiatripholiday" rel="home" class="main-logo">
                            <img src="<?php echo PUBLIC_PATH; ?>images/front_end/logo.png" alt="indiatripholiday">
                        </a>
                    </div>
                </div><!-- /#site-logo -->
                <div class="top-bar-content">
                    <span id="top-bar-text">
                        <!-- <i class="fa fa-phone-square"></i>+91 81-786-595-75 -->
                        <i class="fa fa-envelope"></i>info@indiatripholiday.com
                    </span><!-- /#top-bar-text -->
                </div><!-- /.top-bar-content -->
            </div>
        </div>
    </div><!-- /#top-bar -->

    <!-- Header -->
    <header id="site-header" class="header-front-page style-5">
        <div id="site-header-inner" class="container">
            <div class="wrap-inner">          
                <div class="mobile-button"><span></span></div><!-- //mobile menu button -->

                <nav id="main-nav" class="main-nav">
                    <ul class="menu">
                        <li class="menu-item current-menu-item">
                          <a href="<?php echo HTTP_PATH ; ?>">Home</a>    
                        </li>
                        <li class="menu-item menu-item-has-children"><a href="javascript:;">ABOUT US</a>
                            <ul class="sub-menu">
                                <li class="menu-item"><a href="<?php echo HTTP_PATH.'index/aboutus' ; ?>">INTRODUCTION</a></li>
                                <li class="menu-item"><a href="<?php echo HTTP_PATH.'index/mission' ; ?>">VISION & MISSION</a></li>
                                <li class="menu-item"><a href="<?php echo HTTP_PATH.'index/team' ; ?>">OUR TEAM</a></li>
                                <li class="menu-item"><a href="<?php echo HTTP_PATH.'index/network' ; ?>">OUR NETWORK</a></li>
                            </ul>
                        </li>
    <li class="menu-item menu-item-has-children"><a href="javascript:;">HOLIDAYS PACKAGES</a>
        <ul class="sub-menu">
            <li class="menu-item"><a href="<?php echo HTTP_PATH.'products/index/p/28/t/INTERNATIONAL' ; ?>">INTERNATIONAL</a></li>
            <li class="menu-item"><a href="<?php echo HTTP_PATH.'products/index/p/29/t/INDIA' ; ?>">INDIA</a></li>
        </ul>
    </li>
    <li class="menu-item menu-item-has-children"><a href="javascript:;">MORE SERVICES</a>
        <ul class="sub-menu">
            <li class="menu-item"><a href="<?php echo HTTP_PATH.'products/index/p/30/t/FLIGHTS' ; ?>">FLIGHTS</a></li>
            <li class="menu-item"><a href="<?php echo HTTP_PATH.'products/index/p/31/t/HOTELS' ; ?>">HOTELS</a></li>
            <li class="menu-item"><a href="<?php echo HTTP_PATH.'products/index/p/32/t/BUS' ; ?>">BUS</a></li>
            <li class="menu-item"><a href="<?php echo HTTP_PATH.'products/index/p/33/t/TAXI' ; ?>">TAXI</a></li>
        </ul>
    </li>
                        <li class="menu-item"><a href="<?php echo HTTP_PATH.'index/contact' ; ?>">CONTACT US</a></li>
                    </ul>
            </div>
        </div><!-- /#site-header-inner -->
    </header><!-- /#site-header -->
</div><!-- /#site-header-wrap -->
