<?php

/**
 * CmsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cms');
    }
}