<?php

/**
 * DrawingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DrawingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DrawingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Drawings');
    }
}