<?php

/**
 * Image
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Image extends BaseImage
{

	public static function deleteImg( $id ) {
	
			$qry =Doctrine_Query::create()
				->delete()
				->from('Image')
				->where('id='."'$id'")
				->execute();
				
			if($qry){
				
				return true ;
			}	else{
				
				return false ;
			}
				
		
	}
	
	
	public static function deleteProductImg( $pid ) {
	
		$qry =Doctrine_Query::create()
		->delete()
		->from('Image i')
		->where('i.itemId='."'$pid'")
		->execute();
	
		if($qry){
	
			return true ;
		}	else{
	
			return false ;
		}
	
	
	}
	
	
	
	
// End class	
}