<?php

/**
 * LogoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogoTable extends ImageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Logo');
    }
}