<?php

/**
 * PageAttributeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageAttributeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PageAttributeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PageAttribute');
    }
}