<?php

/**
 * Gallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Site extends BaseSite
{
	
	/**
	 * Author  Raman
	 * @param varchar $params
	 * return Array
	 * Version 1.0
	 */
	
	public static function getgallerylist($params){
		
		$srh = isset($params["searchtext"]) ? $params["searchtext"] : '';
		
		$data = Doctrine_Query::create()
				->select('g.title, g.description, img.path, img.name, cat.id, cat.name, g.created_at, g.updated_at')
				->from('gallery g')
				->leftJoin('g.Image img')
				->leftJoin('g.Category cat')
				->where('g.title LIKE ?', "$srh%")
				->orWhere('g.description LIKE ?', "$srh%")
				->orderBy('g.id DESC');
		
		return Zend_Json::encode(DataTable_Helper::generateDataTableResponse($data, 
				$params, 
				array("__identifier" => 'g.title', 'g.description', 'img.path','img.name','cat.name', 'g.created_at','g.updated_at'),
						array(),
						array()
				));
		exit();
		
		
		
	}
	
	
	/**
	 * Save gallery pics
	 * @author Raman
	 * @version 1.0
	 */
	
	public static function addGallery($category, $title, $description,  $imgfile)
	{
		
		  $galleryObj = new Gallery();
		  $galleryObj->title = BackEnd_Helper_viewHelper::stripSlashesFromString($title);
		  $galleryObj->categoryid = BackEnd_Helper_viewHelper::stripSlashesFromString($category);
		  $galleryObj->description = BackEnd_Helper_viewHelper::stripSlashesFromString($description);
		  
		  $galleryObj->save();
		  $lid = $galleryObj->id;
		  
		  $uploadPath = "images/upload/gallery/";
		  $imagobj = new Image();
		  $imagobj->itemId = $lid;
		  $imagobj->type = "IMGGLR";
		  $imagobj->ext = BackEnd_Helper_viewHelper::getImageExtension( $imgfile );
		  $imagobj->path = $uploadPath;
		  $imagobj->name = $imgfile;
		  $imagobj->save();

			
		  return $lid ;
	}
	
	/**
	 * get to five category
	 * @param string $keyword
	 * @return array $data
	 * @author Raman
	 * @version 1.0
	 */
	public static function searchGalleryPics($keyword) {
	
		$data = Doctrine_Query::create()->select('g.title as name')
		->from("Gallery g")
		->where('g.deleted = 0')
		->andWhere("g.title LIKE ?", "%$keyword%")
		->orderBy("g.title ASC")
		->limit(5)
		->fetchArray();
		return $data;
	}
	
	/**
	 * Delete gallery photo by id
	 * @param integer $params
	 * @author Raman
	 * @version 1.0
	 */
	public static function deletePhotoGallery($params) {
	
		$q = Doctrine_Query::create()->update('Gallery g')
		->set('g.deleted', 1)
		->where('g.id=?', $params['id'])
		->execute();
		
	}
	
}