<body>
<p><?php 
	echo $this->translate('Hi') .' ' .$this->name; ?>,</p>
<p><?php echo $this->translate('Your password has been reset as per your request on our website');?><?php echo $this->host; ?></p>
<p><?php echo $this->translate('Your new password is:');?><strong><?php echo $this->pwd; ?></strong> </p>
<br/>
<p><?php echo $this->translate('Regards');?>,<br/><?php echo $this->translate('Huntapoint Team')?></p>

</body>
