<div id="content-body">
	<div id="aboutbody">
		<ul>
			<li>
				<a href="<?php echo HTTP_PATH."products"; ?>" title="Our Products"><img src="<?php echo PUBLIC_PATH; ?>images/products.jpg" alt=""></a>
				<b>Our Products</b>
				<p>
					We make furniture for the most important place in the world - your home. No matter what your decorating desires or budget requirements are, we have a vast range of styling options and price points. 
				</p>
			</li>
			<li>
				<a href="<?php echo HTTP_PATH."site"; ?>" title="Our Sites"><img src="<?php echo PUBLIC_PATH; ?>images/sites.jpg" alt=""></a>
				<b>Sites We Have Worked On</b>
				<p>
					Sites we have worked you can see here, if you want to know what span we have been covering in Punjab and near by areas..
				</p>
			</li>
			<li>
				<a href="<?php echo HTTP_PATH."gallery"; ?>" title="Our Quality"><img src="<?php echo PUBLIC_PATH; ?>images/quality.jpg" alt=""></a>
				<b>Our Quality</b>
				<p>
					DAF has a huge selection of the latest designs of quality furniture at surprisingly affordable prices for every room of your home including kitchen , living room sets etc.
				</p>
			</li>
			<li>
				<a href="<?php echo HTTP_PATH."contact"; ?>" title="Contact Us"><img src="<?php echo PUBLIC_PATH; ?>images/contact.jpg" alt=""></a>
				<b>We Are Here</b>
				<p>
					We are here to meet your aluminium furniture, kitchen needs, you can call us or send an email for that go to our contact page and we will help you to decorate your home with our quality products.
				</p>
			</li>
		</ul>
		<div>
			<div class="featured">
				<h2>About Us</h2>
				
				<h3>DOABA ALUMINIUM & FABRICATOR</h3>
				<p>Impassioned by aluminium furniture from the past, as well as natural materials, we, at DAF Interiors create our own, contemporary furniture and mainly kitchen we feel we close to perfection.
All our furniture is produced in our own workshop and is manufactured from aluminium, according to the classical method of furniture making.
				</p>
				<p>Models are still drawn by hand, on scale, in order to achieve ideal proportions. DAF only uses functional constructions, not ornamental ones. DAF can offer you several classical pieces, for both indoor and outdoor use.
				</p>
				<p>DAF prefers working with natural, hard-wearing materials, which give the furniture a rich and timeless look.
				</p>
				<p><b>Mr. Manjit Singh </b>director of the factory got more than seven years experience in Dubai in this area, and brought Aluminium Kitchen and Cupboard Desing from Dubai in 2006. Since then we have been giving quality work in many areas of Punjab and near by areas of Punjab.</p>
			</div>
			<div class="section">
				<div class="article">
					<h2>History</h2>
					<p>DOABA ALUMINUM & FABRICATOR(DAF) is a trade association that has represented the interests of the Indian furniture industry for more than 19 years. The furniture factory was started in 1994 to provide high quality furniture at rock bottom prices. While the factory was initially geared for the manufacture of custom made Door & Windows only, the company has since expanded its range to include Living room furniture,modern kitchens, dining room furniture, bedroom furniture, bathroom furniture, Garden furniture and office furniture range.
					</p>
					
				</div>
				<div class="article">
					<h2>From Director's Desk</h2>
					
					<p>Our segment definition is of itself strategic. We are not only intending to satisfy all users of office furniture intended for use with personal computers, but, rather, only those who are most demanding. We are definitely out to address the needs of the high-end buyer, who is willing to pay more for quality.
					<br>In our particular market, we also seek the buyer who appreciates two attributes: the quality of furniture workmanship and the excellence of design, with an understanding of technology and ergonomics built in.</p>
					<img src="<?php echo PUBLIC_PATH; ?>images/hairstyle17.jpg" alt="">
					<a href="#">Manjit Singh</a>
				</div>
			</div>
		</div>
	</div>
</div>