<?php

  $this->headTitle()->append($this->translate('Add Airline'));
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/jquery.validate.js" );
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/addCategory.js" );
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/jquery.textareaCounter.plugin.js");
?>
<div class="wrap columns-2" id="createCategory">
	<form action="<?php echo HTTP_PATH ;?>admin/category/addcategory" method="POST" id="saveCategoryForm" name="saveCategoryForm" enctype="multipart/form-data">
	<input type="hidden" value="" name='iconId' id='iconId' />
	<input type="hidden" value="" name='id' id='id' />
	
		<h1><?php echo $this->translate('Create New Airline'); ?><input type="button"  Value='<?php echo $this->translate('Cancel'); ?>' class="btn ml10" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/category'" /></h1>

		<div id="poststuff" class="metabox-holder has-right-sidebar">
			<div id="post-body">
				<div>
					<div class="mainpage-content">

						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Name'); ?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
									<input type="text" name="categoryName"
										placeholder="<?php echo $this->translate('Name');?>"
										class="span3" maxlength="50"/>
								</div>
							</div>
						</div>

						<!-- <div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Category Icon'); ?></strong></label>
							</div>
							<div class="mainpage-content-right control-group">
								<div class="mainpage-content-right-inner-right-other upload"><?php echo $this->translate('.jpg, .jpeg or .png'); ?></div>
								<div class="mainpage-content-right-inner-left-other">
									<input class="span3 ignore" data-max-size="5097152" onchange="checkFileType(event)" type="file" name="categoryIconNameHidden">

								</div>
							</div>
						</div> -->
						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Description')?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
									<textarea rows="3" name="description"
										placeholder="<?php echo $this->translate('Description')?>"
										id="description" class="input-xlarge mbot bbot ignore"></textarea>
										<input maxlength="500" type="text" class="input-xlarge disabled btop word-count"  id="descriptionLeft" value = "Characters Left: 500" placeholder="Word Count: 28" disabled="disabled">
								</div>
							</div>
						</div>

					</div>

				</div>
			</div>
			<br class="clear">
		</div>
		<div class="mainpage-content-colorbox">
			<button id='saveCategory' type="submit" class="btn btn-large btn-primary fl">
            		<?php echo $this->translate('CREATE AIRLINE')?>
            	</button>
			<a href="<?php echo HTTP_PATH; ?>admin/category" class="fl m10"
				id="cancelCategory"> <strong><?php echo $this->translate('CANCEL')?></strong></a>
		</div>
		<!-- /poststuff -->
	</form>
</div>