 <?php
    $this->headTitle()->append($this->translate('Edit Category'));
    $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/jquery.validate.js" );
	$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/editCategory.js" );
	$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/jquery.textareaCounter.plugin.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
	$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/jquery-ui-1.8.16.custom.css" );
	
	?>
<?php 


$categoryPicturePath = '';
$categoryPictureName = '';
if(file_exists($this->editRec['images']['path'].'thum_'.$this->editRec['images']['name'])) {
	
	$categoryPicturePath = PUBLIC_PATH.$this->editRec['images']['path'].'thum_'.$this->editRec['images']['name'];
	
	$categoryPictureName = $this->editRec['images']['name'];
	$categoryPictureId = $this->editRec['images']['id'];
	

}else {
	
	$categoryPicturePath = PUBLIC_PATH ."images/upload/category/user-avtar.jpg";
	
}
 
?>


	<!-- update category -->
<div id='editCategory' class="wrap columns-2">
	<form action="<?php echo HTTP_PATH ;?>admin/category/editcategory" method="POST" name='updateCategoryForm' id="updateCategoryForm" method=POST enctype=multipart/form-data>
	<input type="hidden" value="<?php echo $categoryPictureId ; ?>" name='iconId' id='iconId' />
	<input type="hidden" value="<?php echo $this->editRec["id"] ; ?>" name='id' id='id' />
	<input type="hidden" value="<?php echo $categoryPictureName ; ?>" name='iconeName' id='iconeName' />
	
		<h1><?php echo $this->translate('Edit Category'); ?><input type="button"  Value='<?php echo $this->translate('Cancel'); ?>' class="btn ml10" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/category'" /></h1>

		<div id="poststuff" class="metabox-holder has-right-sidebar">
			<div id="post-body">
				<div>
					<div class="mainpage-content">

						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Title'); ?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
									<input type="text" name="categoryName" value="<?php echo $this->editRec["name"] ; ?>"
										placeholder="<?php echo $this->translate('Title');?>"
										class="span3" maxlength="50"/>
								</div>
							</div>
						</div>

						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Category Icon'); ?></strong></label>
							</div>
							<div class="mainpage-content-right control-group">
							 <img src ="<?php echo $categoryPicturePath; ?>" alt = "Image" >
								<div class="mainpage-content-right-inner-right-other upload"><?php echo $this->translate('.jpg, .jpeg or .png'); ?></div>
								<div class="mainpage-content-right-inner-left-other">
									<input class="span3 ignore" data-max-size="2097152" onchange="checkFileType(event)" type="file" name="categoryIconNameHidden">

								</div>
							</div>
						</div>
						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Description')?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
									<textarea rows="3" name="description"
										placeholder="<?php echo $this->translate('Description')?>"
										id="description" class="input-xlarge mbot bbot ignore"><?php echo $this->editRec["description"] ; ?></textarea>
										<input maxlength="500" type="text" class="input-xlarge disabled btop word-count"  id="descriptionLeft" value = "Characters Left: 500" placeholder="Word Count: 28" disabled="disabled">
								</div>
							</div>
						</div>

					</div>

				</div>
			</div>
			<br class="clear">
		</div>
		<div class="mainpage-content-colorbox">
			<button id='saveCategory' type="submit" class="btn btn-large btn-primary fl">
            		<?php echo $this->translate('EDIT CATEGORY')?>
            	</button>
			<a href="<?php echo HTTP_PATH; ?>admin/category" class="fl m10"
				id="cancelCategory"> <strong><?php echo $this->translate('CANCEL')?></strong></a>
		</div>
		<!-- /poststuff -->
	</form>
</div>