

<style>


.new-signup-outer-round{
    border-radius:5px;
    border:1px solid #ddd;
    width:100%;
    padding:0;
    text-align:center;
    box-shadow:0 0 5px #ccc;
    background-color:white
}

.mt40{margin-top:40px!important}

.yellow-box-error-box-code{width:800px;margin:50px
auto;align:center;text-align:center;padding:15px;background:-webkit-gradient(linear,left top,left bottom,from(#f3dc97),to(#feebbc));background:-moz-linear-gradient(top,#f3dc97,#feebbc);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#f3dc97',endColorstr='#feebbc');border:1px
solid #e6d08c;-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;box-shadow:1px 2px 2px #ddd}

.mt10{margin-top:20px !important}

.login-form{clear:both;font-size:15px;margin:0
auto;min-height:300px;padding-top:0;text-align:center;width:440px;position:relative}

.error-msg{width:510px;min-height:30px;line-height:20px;color:#c00;float:left;padding:5px
0}

.login-form-row{height:90px;float:left}




.forgot-password-login{position:absolute;top:150px;left:460px}


.login-form{clear:both;font-size:15px;margin:0
auto;min-height:300px;padding-top:0;text-align:center;width:440px;position:relative}.login-form .error-msg{width:510px;min-height:30px;line-height:20px;color:#c00;float:left;padding:5px
0}
.login-form
input{width:428px;height:36px;float:left;padding:10px
0;text-align:center !important;background:url(<?php echo PUBLIC_PATH; ?>/images/front_end/form_input.png) left top no-repeat;font-size:16px;color:#333;margin:0
!important;border:0
none}
#againSet{border-radius:5px 5px 5px 5px;clear:both;color:#FFF;float:left;font-size:15px;min-height:46px;margin:15px
0;text-align:center;width:439px;}.fixedHeight{height:564px!important}.fixedHeight-forgotpwd{height:500px!important}.login-form .blue_btn
a{width:100%;display:block;line-height:46px;font-size:15px;color:#fff;font-weight:bold;text-decoration:none;text-align:center}.login-form .blue_btn a:hover{width:100%;display:block;line-height:46px;font-size:15px;color:#fff;opacity:0.9}.login-form .already-ac{width:439px;height:20px;float:left;clear:both;text-align:center;font-size:13px;color:#333;margin:5px
0 40px 0;font-style:italic}.login-form
a{text-decoration:underline;font-size:13px;color:#449fd4}.login-form a:hover{text-decoration:none;font-size:13px;color:#449fd4}.login_txt{width:964px;height:auto;float:left;margin:40px
18px}.login_txt
h3{width:964px;height:auto;float:left;padding-bottom:30px;border-bottom:1px solid #e3e3e3;font-size:30px;color:#424040;margin-bottom:40px}.login_txt
ul{margin:0;padding:0}.login_txt ul
li{width:33%;float:left;list-style:none}.login_txt ul li
.img{width:68px;height:68px;float:left;border:1px
solid #ddd;box-shadow:0 0 4px #ccc;margin-right:15px}.login_txt ul li .img-txt{width:200px;height:auto;float:left;font-size:14px;color:#333}.login_txt ul li .img-txt
h4{width:200px;height:auto;float:left;font-size:24px;color:#37abe3;margin-bottom:10px;text-align:left}.login_txt ul li .img-txt h4
span{width:200px;height:auto;float:left;font-size:12px;color:#424040}.login_txt ul li .img-txt
p{padding:10px
0 0 0;margin:0;line-height:20px}

.login-form-row input{
 background-color: #FFFFFF;
    border: 1px solid #CCCCCC;
    border-radius: 3px 3px 3px 3px;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
    transition: border 0.2s linear 0s, box-shadow 0.2s linear 0s;
}

.login-form .blue_btn{
background: url("<?php echo PUBLIC_PATH; ?>/images/front_end/blue-btn_bg.jpg") repeat-x scroll left top transparent;
    border-radius: 5px 5px 5px 5px;
    clear: both;
    color: #FFFFFF;
    float: left;
    font-size: 15px;
    height: 46px;
    margin: 15px 0;
    text-align: center;
    width: 439px;
}

.new-signup-outer-round h2{

clear: both;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 24px;
    font-weight: 400;
    line-height: normal;
    margin: 40px 20px 0;
    text-align: center;
    top: 0;
}


</style>

<script type="text/javascript">
<!--

function checkLogin(){

	$("form#login").submit();
}

//-->
</script>


<div class="new-signup-outer-round mt40">
	
       <form autocomplete="off" action="" method="post" id="login" name="login" novalidate="novalidate"> 
        <div class="login-form">
       		<div class="error-msg">
       			<?php
	    	
	    	  	echo $this->message;
	    	 	
	    	?>
       		</div>
            <div class="login-form-row clearfix">
            	<input type="text" placeholder="e-mailaddress" tabindex="1" id="uname" name="uname"><label class="lblerrcls"></label>
            </div>
            <div class="login-form-row clearfix">
            	<input type="password" placeholder="password" tabindex="2" value="" id="pwd" name="pwd"><label class="lblerrcls"></label>
                
            <a href="<?php echo HTTP_PATH.'user/register'; ?>">Create your account here (Sign up)</a>
            </div>
            
            <div class="blue_btn" id="changeWhenLogin">
            	<a onclick="checkLogin();" tabindex="3" href="javascript:void(0);">Sign In</a>
            </div>
            <div class="already-ac">
            	&nbsp;
            </div>
       
       <div class="clr"></div>
       </div> 
       </form>
       
    </div>
    
    <div class="clr"></div>