

<link href='http://fonts.googleapis.com/css?family=Dancing+Script:700|Mako' rel='stylesheet' type='text/css'>
<?php

$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "js/front_end/jackbox/preview.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "js/front_end/jackbox/css/jackbox.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "js/front_end/jackbox/css/jackbox_hovers.css" );

?>
        <!--[if lt IE 9]>
        	<link href="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/css/jackbox-ie8.css" rel="stylesheet" type="text/css" />
        	<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        
        <!--[if gt IE 8]><link href="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/css/jackbox-ie9.css" rel="stylesheet" type="text/css" /><![endif]-->

<?php 


$this->headScript ()->appendFile ( "http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/front_end/jackbox/js/libs/jquery.address-1.5.min.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/front_end/jackbox/js/libs/Jacked.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/front_end/jackbox/js/jackbox-swipe.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/front_end/jackbox/js/jackbox.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/front_end/jackbox/js/libs/StackBlur.js" );


echo $this->headStyle ();
echo $this->headLink ();
echo $this->headScript ();



//$imagesArray = $this->imagesArray;


?>

        <script type="text/javascript">
		
			jQuery(document).ready(function() {


				/* ******************** */
				/* MINIMAL JACKBOX CALL */
				/* ******************** */
				jQuery(".jackbox[data-group]").jackBox("init");

				//jQuery(".jackbox-social").hide();				
				
				
				/* ************* */
				/* DYNAMIC CALLS */
				/* ************* */
			
			});
		
		</script>

<style>
<!--
#container{
float: none;
}

.jackbox-social{
	
	display: none;
	
}
-->
</style>
        

 <div id="wrapper">
        	
            <div id="holder">
                

            	 <div id="container"> 
                    
                    <figure class="box">

						<a class="jackbox" 
                        
                        	data-group="images" 
                            data-thumbnail="<?php echo $this->firstimg["thumbSrc"]; ?>" 
                            data-thumbTooltip="<?php echo $this->firstimg["title"]; ?>" 
                            data-title="<?php echo $this->firstimg["title"]; ?> " 
                            data-description="#description_1" 
                            href="<?php echo $this->firstimg["src"]; ?>" > <!-- end opening tag -->
    
                            <!-- thumbnail -->
                            <div class="jackbox-hover jackbox-hover-blur jackbox-hover-magnify">
                            <p>Click for Show</p></div>
                            <img src="<?php echo $this->firstimg["thumbSrc"]; ?>" width="180" height="150" alt="responsive lightbox" />
                            
                        </a>
                        
                        
                        <ul class="jackbox-hidden-items">
                        	
                            <!-- for hidden items, "data-href" is used instead of the regular "href" attribute that regular links use like above -->
					<?php foreach($this->restall as $rows){ ?>
                        <li class="jackbox" data-group="images" data-title="<?php echo $rows ["title"] ;?>" data-description="#description_1" data-thumbnail="<?php echo $rows ["thumbSrc"] ;?>" data-href="<?php echo $rows ["src"] ;?>"></li>
                    <?php } ?>        
                            <!-- <li class="jackbox" data-group="images" data-title="Leather Coat" data-description="#description_1" data-thumbnail="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/img/thumbs/3a.jpg" data-href="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/img/photos/3.jpg"></li>
                            <li class="jackbox" data-group="images" data-title="Man Wearing Scarf" data-description="#description_1" data-thumbnail="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/img/thumbs/4a.jpg" data-href="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/img/photos/4.jpg"></li>
                            <li class="jackbox" data-group="images" data-title="Cool Sunglasses" data-description="#description_1" data-thumbnail="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/img/thumbs/5a.jpg" data-href="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/img/photos/5.jpg"></li>
                            <li class="jackbox" data-group="images" data-title="Coffee Mug" data-description="#description_1" data-thumbnail="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/img/thumbs/6a.jpg" data-href="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/img/photos/6.jpg"></li>
                            <li class="jackbox" data-group="images" data-title="Woman Wearing Rings" data-description="#description_1" data-thumbnail="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/img/thumbs/7a.jpg" data-href="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/img/photos/7.jpg"></li>
                            <li class="jackbox" data-group="images" data-title="Awesome Car" data-description="#description_1" data-thumbnail="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/img/thumbs/8a.jpg" data-href="<?php echo PUBLIC_PATH; ?>js/front_end/jackbox/img/photos/8.jpg"></li> -->
                        
                        </ul>
                    </figure>				
  <!-- End slider code -->
  
  
  </div>
      <div class="clr"></div>
</div></div>

</div>