<?php
$this->headTitle()->append($this->translate('Order'));

$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.ui.widget.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.iframe-transport.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.fileupload.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.fileupload-fp.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.fileupload-ui.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/common.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/gallery.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
?>

 <style>

div.dataTables_wrapper table tbody tr td
	{
	padding-bottom: 15px; 
	}
	
div#wordsListTable_filter
{
	display : none;
}
</style>
<!-- Div for user list  -->

<div class='wrap columns-2' id='regionListDiv'>
<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
<br><div class ="mainpage-content-colorbox success" id="removemsg">
<?php if($this->messageSuccess!=''){?>
<span class="successserver"><?php echo $this->messageSuccess; ?></span>
<?php }?>
<?php if($this->messageError!=''){?>
<span class="errorserver"><?php echo $this->messageError; ?></span>
<?php } ?>
</div>
<?php }?>
<h1 class="fl"><?php echo $this->translate('Manage Orders');?></h1>

	<!-- <input type="button"  onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/product/add'" Value='<?php echo $this->translate('Add New Product'); ?>'  name='addNew'  class="btn ml10" style="margin-bottom: -39px;" /> -->
          	<div class="clear"></div>
          
          <div class="mainpage-content-colorbox">
                
                <form class="form-search" name="searchForm" onsubmit="return false;">
			      <div class="fl">                   
                         <input type="text" id='searchProduct' name='searchProduct' placeholder="Search..." class="span5">
                        <button onclick="javascript:getproductsList(searchProduct.value)" class="btn btn-primary">Search</button>
                    </div>             	
                    <!--<div class="fl ml15 fillterDiv"> 
                      <select id='selectRole'>
                      </select>
                    </div> -->                         
                </form>
            
            </div>  
            
		<table id="productListTable" class="table table-bordered table-striped">
			<thead>
	            <tr>
	                <th><?php echo $this->translate('Name'); ?></th>
	                <th><?php echo $this->translate('Phone'); ?></th>
	                <th><?php echo $this->translate('Travel Date & Time'); ?></th>
	                <th><?php echo $this->translate('Return Date & Time'); ?></th>
	                <th><?php echo $this->translate('From'); ?></th>
	                <th><?php echo $this->translate('To'); ?></th>
	                <th><?php echo $this->translate('Status'); ?></th>
	                <!-- <th><?php //echo $this->translate('Qty Member'); ?></th> -->
	                <th><?php echo $this->translate('Action'); ?></th>
	            </tr>
	        </thead>
	    </table>
</div><!-- End code of list users -->

